### PR TITLE
Remove unnecessary namespace polution

### PR DESCRIPTION
**Pull request by sodero**

### CODE REVIEW

**Comment by eyalroz** [comment]
Please make this PR against the develop branch..

**Comment by eyalroz** [comment]
I believe the addition of `static` already happened on the `develop` branch last month. So rejecting this PR...

**Comment by eyalroz** [comment]
... and now I've also added the README comment fix from the master branch. So, all done here...

After I finish with the current "load" of PRs and the MISRA changes, I'll probably make another release.

**Comment by sodero** [comment]
Excellent, thank you for your efforts with printf. It's very useful.

**Comment by eyalroz** [comment]
@sodero : I feel like a bit like a janitor with this project... after some initial bug fixes, almost all of the changes here are not about making anything work, just about making things "tidy" by different people's standards. One guy wants MISRA compliance, another wants single header, another wants to include the CMakeLists from another project...

**Pull request closed without merging**
