### PR TITLE
Fixes #84: Choice of `float`/`double`

### LINKED ISSUE #84: Compile option to process floating point values in single-precision, internally
I have a project where I use single precision floats, but no doubles.
Problem is, that printf processes all floating point values as doubles, even if the caller is content with single precision formatting. On devices without double-FPU, this pulls in `__aeabi_dsub`, `__aeabi_dmul` and the likes, which are several kilobytes large.

My suggestion is to add a compile option so that floating point values are formatted with single precision.

The value would still be passed as a double to `printf`, which would then be converted to float.
Some of the required functionality seems to be already there, via the `#if DBL_MANT_DIG == 24` define.

### PR DESCRIPTION
**Pull request by eyalroz**
Fixes #84.

### CODE REVIEW

**Comment by jrahlf** [comment]
I think it looks good so far.
- previously platforms where double is 32-bit (GCC-AVR) were supported implicitly (without documentation), this update breaks this unless `PRINTF_USE_DOUBLE_INTERNALLY `is set to 0. Either the code or the documentation should be updated accordingly.
- As shown in the other PR, to get the full benefit, one must (try to) also get rid of the int64_t<>float conversions, but this can also be attempted in another PR

**Comment by eyalroz** [comment]
> this update breaks this unless PRINTF_USE_DOUBLE_INTERNALLY is set to 0

It shouldn't! If that happens, I have a bug. I tried to support double = 32-bits even when `PRINTF_USE_DOUBLE_INTERNALLY` is 1.

>  but this can also be attempted in another PR

One step at a time :-) ... also, I've created [v6.0.0](https://github.com/eyalroz/printf/releases/tag/v6.0.0) with my recent changes. Would appreciate feedback there as well.

**Comment by jrahlf** [comment]
> > this update breaks this unless PRINTF_USE_DOUBLE_INTERNALLY is set to 0
> 
> It shouldn't! If that happens, I have a bug. I tried to support double = 32-bits even when `PRINTF_USE_DOUBLE_INTERNALLY` is 1.

I misread the code, I think you are right.

**Comment by eyalroz** [comment]
Just so you know, though, I'm not hurrying to merge this before I get some feedback of the v6.0.0 pre-release; and properly release it. Then this can go on the development branch.

**Comment by crazybolillo** [comment]
Hello, I see this was merged into develop. I personally tried this new option on a Cortex M4 with FP unit and it reduced code size by around 800 bytes, so that is good. Also my program still works fine. Thanks for the work, just thought I would give a testimony to the fact this works hehe.

**Comment by eyalroz** [comment]
Thank you, @crazybolillo , it's nice to get positive feedback :-)

**Pull request merged**
