### PR TITLE
Propagate include directory when consuming this library from CMake

### PR DESCRIPTION
**Pull request by KKoovalsky**
This allows to properly consume the library when it is used via `add_subdirectory` or `FetchConten` module.

Consider CMake code:

    FetchContent_Declare(printf_library
        GIT_REPOSITORY https://github.com/eyalroz/printf.git
        GIT_TAG v5.0.0
    )
    FetchContent_MakeAvailable(printf_library)

Then consume the `printf` library created within "eyalroz/printf" project:

    add_executable(main main.cpp)
    target_link_libraries(main PRIVATE printf)

Inside 'main.cpp':

    #include "printf.h" // ERROR: No such file or directory OR
                        // includes "/usr/include/printf.h' which comes
                        // installed with GNU C library

    #include "printf/printf.h" // ERROR: No such file or directory

After this commit is applied, one can consume the library from C/C++ code with:

    #include "printf/printf.h"

### CODE REVIEW

**Comment by eyalroz** [comment]
So, most of what you suggest here seems to already have been done in #58 . There seems to be one relevant commit. ... but that commit has a super-long commit message, which belongs here in the discussion or is just the text you added on the issue you filed. Let me see..

**Comment by eyalroz** [comment]
I think I've _effectively_ merged your PR, even though GitHub doesn't recognize that fact... can you check and make sure the HEAD of the develop branch works as you would expect?

**Comment by KKoovalsky** [comment]
I guess that you have rewritten the history, because the `develop` branch is missing two commits since yesterday. This PR included only this commit: [bbc87a4995acb6523e36f618f96cdaf2d326018b
](https://github.com/eyalroz/printf/pull/66/commits/bbc87a4995acb6523e36f618f96cdaf2d326018b). The two missing commits must have been removed and I guess that `git push -f ...` has been used.

**Comment by eyalroz** [comment]
@KKoovalsky : Yes, my personal custom is that the master branch is "pristine" with no history rewrites, but on the develop branch I often change things retroactively.

Anyway, I'm glad that, eventually, the necessary change strictly for supporting add_subdirectory was pretty small (or arguably, nothing was strictly justified by this kind of use and everything sort of makes sense even for the regular use of the repository). Thanks again and now onto the aliasing business.

**Pull request closed without merging**
